---

- name: Configure ~/.ssh/authorized_keys for users
  authorized_key:
    key: "{{ item.ssh_keys | join('\n') | string }}"
    user: "{{ item.name }}"
  with_flattened:
    - "{{ users_list }}"
  when: (item.name is defined and item.name and item.name != "root") and
          (item.state is undefined or (item.state is defined and item.state != "absent")) and
          (item.createhome is undefined or item.createhome) and
          (item.ssh_keys is defined and item.ssh_keys)
  tags:
    - users
    - ssh_keys

- name: Remove revoked keys from user account
  authorized_key:
    key: "{{ users_revoked_ssh_keys | join('\n') }}"
    user: "{{ item.name }}"
    state: absent
  become_user: "{{ item.name }}"
  with_flattened:
    - "{{ users_list }}"
  when: (users_revoked_ssh_keys is defined and (users_revoked_ssh_keys | length > 0)) and
          (item.name is defined and item.name and item.name != "root") and
          (item.state is undefined or (item.state is defined and item.state != "absent")) and
          (item.createhome is undefined or item.createhome)
  tags:
    - users
    - ssh_keys
